name: CI/CD go fiber EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1

      - name: Build app
        run: go build -o clarifyAPI .

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clarifyAPI
          path: clarifyAPI

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: fiber-app
          path: .

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > awspem.pem
          chmod 600 awspem.pem

      - name: Deploy to EC2
        run: |
          scp -i awspem.pem clarifyAPI ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/apps/clarify
          ssh -i awspem.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart clarify || true"
